# Generated by Django 4.2.4 on 2023-08-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_user_address_user_vaccinationcenter_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationslot',
            name='available_slots',
            field=models.IntegerField(default=10),
        ),
    ]
